### ISSUE TITLE
Aufgabenverteilungs-Diagramm

### ISSUE THREAD

**Issue by fxedel** [ApoapsisHGV/ApoapsisHGV.github.io#4]
@hargoniX: Niklas hätte auch gerne so eine Diagram wie die hier [planat.earth/de/team](http://planat.earth/de/team)
@fxedel: @hargoniX Ja dann mach doch eins :)
@hargoniX: Du als Schüler welcher den Grafikdesigkurs besuchst bist dazu sicherlich besser in der Lage als ich.
Oder gar Niklas selbst

**Comment by NiklasC** [comment]
Leute das war ein Scherz, falls ihr es nicht erkannt habt. Um ehrlich zu sein finde ich das Diagram keine gute Idee, vor allem da wir nur 4 oder 5 und nicht 8 Leute sind
